extends: default

rules:
  document-start: disable
  quoted-strings:
    required: only-when-needed
    extra-allowed:
      - "{|}"
      - ^[0-9][0-9]:[0-9][0-9]$
      - ^0 0 \* \* 0$
  key-duplicates: {}
  octal-values:
    forbid-implicit-octal: true
  line-length:
    max: 120
    level: warning
  truthy:
    allowed-values: ['true', 'false', 'on', 'off']
  comments:
    min-spaces-from-content: 2

ignore: |
  node_modules/
  coverage/
  dist/
  build/
  .git/
  *.min.yml
  *.min.yaml
  pnpm-lock.yaml
  package-lock.json
  yarn.lock
